Initial pes structures
xMOROx/rtpeeker pull request #4
Opened 2024-04-29 19:21 UTC by erizee

2024-04-29 19:28 UTC, xMOROx requested changes

2024-04-29 19:28 UTC, xMOROx commented on common/src/pes/pes.rs
> +    header: Option<OptionalPesHeader>,
chyba zmieniłbym `header` na `optional_header`

2024-05-03 06:32 UTC, xMOROx commented
Wydaje mi się, że nie ma potrzeby pisać prefiksa `pes_` w polach struktury bo ona sama już nadaje kontekst @erizee

2024-05-03 11:50 UTC, erizee commented
> Wydaje mi się, że nie ma potrzeby pisać prefiksa `pes_` w polach struktury bo ona sama już nadaje kontekst @erizee

@xMOROx Zostawiłem je dla zgodności z opisem struktury w h222, ale jak lepiej będzie bez tego to moge usunąć

2024-05-03 12:54 UTC, xMOROx commented
Wydaje mi się sensowniejsze usunięcie ale może się @dominikpuz wypowiedzieć

2024-05-07 09:05 UTC, xMOROx approved these changes

2024-05-07 09:05 UTC, merged